config/routes.rb
Rails.application.routes.draw do

  get 'posts/index'
  get 'posts/show'
  get 'popular', to: 'posts#popular'
  get 'handpicked', to: 'posts#handpicked'
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post
	include HTTParty

	base_uri 'https://api.500px.com/v1/photos'
	default_params 	only: "nature", rpp: "12", 
					image_size: "600", 
					consumer_key: Figaro.env.px_consumer_key

	def self.for feature
		get("", query: {feature: feature}, verify: false).parsed_response
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    #do pagination (infinite scrolling)
    #handle bad request connection
    #do tests
  	feature = "fresh_today"  
    response = Post.for(feature)
  	@posts = response["photos"]
  end

  def show
  end

   def handpicked
    #do pagination (infinite scrolling)
    #handle bad request connection
    #do tests
    feature = "editors"  
    response = Post.for(feature)
    @posts = response["photos"]
  end

  def popular
    #do pagination (infinite scrolling)
    #handle bad request connection
    #do tests
    feature = "popular"  
    response = Post.for(feature)
    @posts = response["photos"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/posts_helper.rb
module PostsHelper
	def owner_from(city, country)
		# make test
		[city, country].reject(&:blank?).join(", ").to_s
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calmer</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', 
    	'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600&amp;subset=latin-ext',
    	 media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post_item.html.erb
<% user = post["user"] %>
<% owner_from = owner_from(user["city"], user["country"]) %>

<div class="post_item">
	<div class="post_header">
		<div class="post_profile">
			<div class="avatar">
				<%= image_tag user["userpic_url"] %>
			</div>
			<a href="https://500px.com/<%= user["username"] %>" class="body">
				<div><span class="bold"><%= user["fullname"] %></span> 
          <% if owner_from != "" %>
            <span class="from"> <%= owner_from(user["city"], user["country"]) %></span>
          <% end %>
        </div>
			</a>
		</div>
	</div>
	<a href="https://500px.com<%= post["url"] %>" class="post_picture">
		<%= image_tag post["image_url"] %>
	</a>
	<div class="post_details">
		<h3 class="title mt_small"><%= post["title"] %></h3>
		<p class="l"><%= post["description"] %></p>
	</div>
</div>

app/views/posts/_posts.html.erb
<div class="posts_feed clearfix">
	<div class="mt_small">
		<% posts.each do |post|%>
		<%= render partial: "posts/post_item", locals: {post: post} %>
	<% end %>
	</div>
</div>

app/views/posts/handpicked.html.erb
<%= render "shared/home-header" %>
<%= render partial: "shared/mobile_footer" %>

<div class="mt_header">
	<%= render partial: "posts/posts", locals: {posts: @posts} %>
</div>

app/views/posts/index.html.erb
<%= render "shared/home-header" %>
<%= render partial: "shared/mobile_footer" %>

<div class="posts_feed mt_header">
    <div class="info_tab">
        <h1 class="bold">Hi there,</h1>
        <p class="lighter mt_small">I was about to build this site to try and "re-learn" Ruby on Rails(5) in my spare time. But at some point I came to realize that I don't want to jump on this ruby train again. </p>
        <p class="lighter mt_small">So I am sorry that this is just a torso of what it should be. You can find <a href="https://github.com/vosmik/calmer" class="text-link">Github repository here</a>. Calmer is consuming <a href="https://github.com/500px/api-documentation" class="text-link">500PX' API</a>. It runs on free Heroku, so sorry for the performance :).</p>
        <h3 class="mt_small bold">Shortly about me</h3>
        <p class="lighter mt_small"> Somehow, Elixir (built on top of Erlang VM) got in my way for doing APIs and Ember.js on the frontend side and I really felt in love with both of them and especially (thanks to Elixir) I felt in love with functional programming.</p>

        <p class="lighter mt_small">During my journey, I realized the potential of the "new" JavaScript (for both - frontend and backend) and I decided, for the first time in my live, to choose just this one JS thing and learn it well, together with React and hopefully React Native and Node.js.
        </p> 
        <p class="lighter mt_small">I really love doing frontend / UX jobs. I am a self learner, a passionate problem solver and full-time dreamer.</p>
        <p class="mt_small bold">Keep calmer :)</p>
        <div class="info_tab_icon">
            <%= image_tag "icons/hi_face" %>
        </div>
    </div>
</div>

<%= render partial: "posts/posts", locals: {posts: @posts} %>

app/views/posts/popular.html.erb
<%= render "shared/home-header" %>
<%= render partial: "shared/mobile_footer" %>

<div class="mt_header">
	<%= render partial: "posts/posts", locals: {posts: @posts} %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<div class="mt_header">
	<p>Find me in app/views/posts/show.html.erb</p>
</div>

app/views/shared/_home-header.html.erb
<div class="header">
  <div class="header_left">
    <%= link_to root_path, :class=>"header_logo" do %>
      <%= image_tag "logos/logo_small" %>
    <% end %>
  </div>

  <div class="header_right">
    <div class="header_link_holder">
      <a target="_blank" href="https://github.com/vosmik" class="header_icon github">
        <%= image_tag "icons/github", :class => "" %>
      </a>
    </div>
    <div class="header_link_holder">
      <a target="_blank" href="https://www.instagram.com/v8ickaa/" class="header_icon instagram">
        <%= image_tag "icons/instagram", :class => "" %>
      </a>
    </div>
    <div class="header_link_holder">
      <a target="_blank" href="https://www.freecodecamp.com/vosmik" class="header_icon free_code_camp">
        <%= image_tag "icons/freeCodeCamp", :class => "" %>
      </a>
    </div>
  </div>

  <div class="header_content">
    <div class="tab_nav clearfix">
      <a href="" class="active">Calmer</a>
      <a href="" class="blank">Blog</a>
    </div>
    <div class="sub_nav">
        <%= link_to "new", root_path, :class => current_class?(root_path) %>
        <%= link_to "popular", popular_path, :class => current_class?(popular_path) %>
        <%= link_to "handpicked", handpicked_path, :class => current_class?(handpicked_path) %>
    </div>
  </div>
</div>

app/views/shared/_mobile_footer.html.erb
<div class="mobile_footer">
	<div class="footer_link_holder">
      <a href="/" class="header_icon mobile_logo">
        <%= image_tag "logos/c_only", :class => "" %>
      </a>
    </div>
	<div class="footer_link_holder">
      <a target="_blank" href="https://github.com/vosmik" class="header_icon github">
        <%= image_tag "icons/github", :class => "" %>
      </a>
    </div>
    <div class="footer_link_holder">
      <a target="_blank" href="https://www.instagram.com/v8ickaa/" class="header_icon instagram">
        <%= image_tag "icons/instagram", :class => "" %>
      </a>
    </div>
    <div class="footer_link_holder">
      <a target="_blank" href="https://www.freecodecamp.com/vosmik" class="header_icon free_code_camp">
        <%= image_tag "icons/freeCodeCamp", :class => "" %>
      </a>
    </div>
</div>